;; This logfile was generated automatically by `xindy'
;; at 30.03.2022  18:58:23
;; Indexstyle: "/var/folders/m3/_my7yl913gs59vc5prp0lrzh0000gn/T/cDR3GXQvwT", Rawindex: "/var/folders/m3/_my7yl913gs59vc5prp0lrzh0000gn/T/bYOqbKpKdv", Output: "memoria.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€¼" -> "G"