;; This logfile was generated automatically by `xindy'
;; at 18.04.2022  15:35:54
;; Indexstyle: "/var/folders/m3/_my7yl913gs59vc5prp0lrzh0000gn/T/if425rHGgq", Rawindex: "/var/folders/m3/_my7yl913gs59vc5prp0lrzh0000gn/T/txiBg6ffu8", Output: "memoria.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€¼" -> "G"